---
title: "About"
about:
  template: trestles
  links:
    - icon: envelope
      href: "mailto: abiprakash007@gmail.com"
    - icon: github
      href: https://github.com/prakaa
    - icon: linkedin
      href: https://www.linkedin.com/in/abi-prakash-69628479/
---

## Me

I'm a [PhD candidate at the Collaboration on Energy and Envrionmental Markets](https://www.ceem.unsw.edu.au/staff/abhijith-prakash) at UNSW Sydney. I'm looking at how risks to system balancing might be managed in power systems and electricity markets with growing penetrations of renewable energy and storage. Much of my work is related to the Australian National Electricity Market (NEM).

Beyond my research work, I have a pretty broad range of interests:

- Political economy of energy transition and climate change
- Policy frameworks and market design for energy systems
- Resource and system (production-cost) modelling through optimisation models
- Understanding system-level technical constraints that arise from power flow studies and dynamic assessments

Always happy to have a chat, so if you're interested in chatting please get in touch.

## This website

This website was made using [Quarto](https://quarto.org/docs/websites>), a great extension to the already amazing [pandoc](https://pandoc.org/).



